name: Run tests

on: [pull_request, push]

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Restore gems from cache
        uses: actions/cache@v2
        env:
          cache-name: ruby-gems-cache
        with:
          path: ./.gems
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/dbml.gemspec') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install gems
        run: bundle install --path=./.gems --jobs=4 

      - name: Run tests
        run: bundle exec rake test
